export const flightLists = [
    {
      airlineLogo: 'https://placehold.co/100x100/D92D31/FFFFFF?text=AirAsia&font=sans',
      airlinename: 'Air Asia',
      departureTime: "23:35",
      arrivalTime: "01:45",
      totalDuration: "02h 10m",
      isNonStop: true,
      ticketPrice: "₹ 2,500",
      isRefundable:  true,
      isFreeMeal: true,
    },
    {
      airlineLogo: 'https://placehold.co/100x100/D92D31/FFFFFF?text=AirAsia&font=sans',
      airlinename: 'Air Asia',
      departureTime: "23:35",
      arrivalTime: "01:45",
      totalDuration: "02h 10m",
      isNonStop: true,
      ticketPrice: "₹ 2,500",
      isRefundable:  true,
      isFreeMeal: true,
    },
    {
      airlineLogo: 'https://placehold.co/100x100/D92D31/FFFFFF?text=AirAsia&font=sans',
      airlinename: 'Air Asia',
      departureTime: "23:35",
      arrivalTime: "01:45",
      totalDuration: "02h 10m",
      isNonStop: true,
      ticketPrice: "₹ 2,500",
      isRefundable:  true,
      isFreeMeal: true,
    },
    {
      airlineLogo: 'https://placehold.co/100x100/D92D31/FFFFFF?text=AirAsia&font=sans',
      airlinename: 'Air Asia',
      departureTime: "23:35",
      arrivalTime: "01:45",
      totalDuration: "02h 10m",
      isNonStop: true,
      ticketPrice: "₹ 2,500",
      isRefundable:  true,
      isFreeMeal: true,
    },
    {
      airlineLogo: 'https://placehold.co/100x100/D92D31/FFFFFF?text=AirAsia&font=sans',
      airlinename: 'Air Asia',
      departureTime: "23:35",
      arrivalTime: "01:45",
      totalDuration: "02h 10m",
      isNonStop: true,
      ticketPrice: "₹ 2,500",
      isRefundable:  false,
      isFreeMeal: true,
    },
    {
      airlineLogo: 'https://placehold.co/100x100/D92D31/FFFFFF?text=AirAsia&font=sans',
      airlinename: 'Air Asia',
      departureTime: "23:35",
      arrivalTime: "01:45",
      totalDuration: "02h 10m",
      isNonStop: true,
      ticketPrice: "₹ 2,500",
      isRefundable:  true,
      isFreeMeal: true,
    },
    {
      airlineLogo: 'https://placehold.co/100x100/D92D31/FFFFFF?text=AirAsia&font=sans',
      airlinename: 'Air Asia',
      departureTime: "23:35",
      arrivalTime: "01:45",
      totalDuration: "02h 10m",
      isNonStop: true,
      ticketPrice: "₹ 2,500",
      isRefundable:  true,
      isFreeMeal: true,
    },
    {
      airlineLogo: 'https://placehold.co/100x100/D92D31/FFFFFF?text=AirAsia&font=sans',
      airlinename: 'Air Asia',
      departureTime: "23:35",
      arrivalTime: "01:45",
      totalDuration: "02h 10m",
      isNonStop: true,
      ticketPrice: "₹ 2,500",
      isRefundable:  true,
      isFreeMeal: true,
    },
   
];
